/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ActiveAgencyToReturnDto
 */
export interface ActiveAgencyToReturnDto {
    /**
     * کد آژانس
     * @type {number}
     * @memberof ActiveAgencyToReturnDto
     */
    'agnecyId'?: number;
    /**
     * نام آژانس
     * @type {string}
     * @memberof ActiveAgencyToReturnDto
     */
    'agencyName'?: string | null;
    /**
     * لوگو
     * @type {string}
     * @memberof ActiveAgencyToReturnDto
     */
    'logo'?: string | null;
    /**
     * نام شهر
     * @type {string}
     * @memberof ActiveAgencyToReturnDto
     */
    'cityName'?: string | null;
}

