/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdAnalyticsDto
 */
export interface AdAnalyticsDto {
    /**
     * کد مشاور
     * @type {number}
     * @memberof AdAnalyticsDto
     */
    'adviserId'?: number;
    /**
     * نوع آگهی
     * @type {string}
     * @memberof AdAnalyticsDto
     */
    'adType'?: AdAnalyticsDtoAdTypeEnum;
    /**
     * کد آگهی
     * @type {number}
     * @memberof AdAnalyticsDto
     */
    'adId'?: number;
    /**
     * تعداد درخواست شماره مشاور
     * @type {number}
     * @memberof AdAnalyticsDto
     */
    'adviserPhoneRequest'?: number;
    /**
     * تعداد درخواست شماره آژانس
     * @type {number}
     * @memberof AdAnalyticsDto
     */
    'agencyPhoneRequest'?: number;
    /**
     * تعداد مشاهده آگهی
     * @type {number}
     * @memberof AdAnalyticsDto
     */
    'visitCount'?: number;
}

export const AdAnalyticsDtoAdTypeEnum = {
    Sell: 'sell',
    Let: 'let'
} as const;

export type AdAnalyticsDtoAdTypeEnum = typeof AdAnalyticsDtoAdTypeEnum[keyof typeof AdAnalyticsDtoAdTypeEnum];


