/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdHitStaticDto
 */
export interface AdHitStaticDto {
    /**
     * تعداد کل آگهی ها
     * @type {number}
     * @memberof AdHitStaticDto
     */
    'totalAdsCount'?: number;
    /**
     * مجموع نمایش آگهی ها
     * @type {number}
     * @memberof AdHitStaticDto
     */
    'hitCount'?: number;
    /**
     * مجموع کلیک آگهی ها
     * @type {number}
     * @memberof AdHitStaticDto
     */
    'clickCount'?: number;
    /**
     * مجموع مشاوران
     * @type {number}
     * @memberof AdHitStaticDto
     */
    'advisersCount'?: number;
}

