/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdPost
 */
export interface AdPost {
    /**
     * کد آگهی
     * @type {number}
     * @memberof AdPost
     */
    'adId'?: number;
    /**
     * کد ساختمان
     * @type {number}
     * @memberof AdPost
     */
    'buildingId'?: number;
    /**
     * کد پیگیری
     * @type {number}
     * @memberof AdPost
     */
    'trackingCode'?: number;
}

