/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddressToReturnDto
 */
export interface AddressToReturnDto {
    /**
     * کد آدرس
     * @type {number}
     * @memberof AddressToReturnDto
     */
    'addressId'?: number;
    /**
     * کد ساختمان
     * @type {number}
     * @memberof AddressToReturnDto
     */
    'buildingId'?: number;
    /**
     * Main
     * @type {string}
     * @memberof AddressToReturnDto
     */
    'main'?: string | null;
    /**
     * Detail
     * @type {string}
     * @memberof AddressToReturnDto
     */
    'detail'?: string | null;
    /**
     * قابل رویت
     * @type {boolean}
     * @memberof AddressToReturnDto
     */
    'visible'?: boolean | null;
    /**
     * ایجاد شده در
     * @type {string}
     * @memberof AddressToReturnDto
     */
    'createdAt'?: string | null;
    /**
     * ویرایش شده در
     * @type {string}
     * @memberof AddressToReturnDto
     */
    'updatedAt'?: string | null;
    /**
     * حذف شده در
     * @type {string}
     * @memberof AddressToReturnDto
     */
    'deletedAt'?: string | null;
}

