/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddressForCreateDto
 */
export interface AddressForCreateDto {
    /**
     * Main
     * @type {string}
     * @memberof AddressForCreateDto
     */
    'main'?: string | null;
    /**
     * Detail
     * @type {string}
     * @memberof AddressForCreateDto
     */
    'detail'?: string | null;
    /**
     * قابل رویت
     * @type {boolean}
     * @memberof AddressForCreateDto
     */
    'visible'?: boolean | null;
}

