/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Advisers } from './advisers';

/**
 * 
 * @export
 * @interface AdvisersLanding
 */
export interface AdvisersLanding {
    /**
     * لیست رکورد ها
     * @type {Array<Advisers>}
     * @memberof AdvisersLanding
     */
    'data'?: Array<Advisers> | null;
    /**
     * صفحه ی جاری
     * @type {number}
     * @memberof AdvisersLanding
     */
    'currentPage'?: number;
    /**
     * تعداد کل صفحات
     * @type {number}
     * @memberof AdvisersLanding
     */
    'totalPages'?: number;
    /**
     * تعداد رکورد در هر صفحه
     * @type {number}
     * @memberof AdvisersLanding
     */
    'pageSize'?: number;
    /**
     * تعداد کل رکورد ها
     * @type {number}
     * @memberof AdvisersLanding
     */
    'totalCount'?: number;
    /**
     * <meta property=\"og:title\" content=\"\" />  <meta property=\"og:title\" content=\"The Rock\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogTitle'?: string | null;
    /**
     * <meta property=\"og:type\" content=\"product\" />  <meta property=\"og:type\" content=\"video.movie\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogType'?: string | null;
    /**
     * <meta property=\"og:url\" content=\"https://www.imdb.com/title/tt0117500/\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogUrl'?: string | null;
    /**
     * <meta property=\"og:image\" content=\"https://ia.media-imdb.com/images/rock.jpg\" />  <meta property=\"og:image\" content=\"\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogImage'?: string | null;
    /**
     * <meta property=\"og:image:width\" content=\"500\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogImageWidth'?: string | null;
    /**
     * <meta property=\"og:image:height\" content=\"500\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogImageHeight'?: string | null;
    /**
     * <meta property=\"og:audio\" content=\"https://example.com/bond/theme.mp3\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogAudio'?: string | null;
    /**
     * <meta property=\"og:description\" content=\"Sean Connery found fame and fortune as the suave, sophisticated British agent, James Bond.\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogDescription'?: string | null;
    /**
     * <meta property=\"og:determiner\" content=\"the\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogDeterminer'?: string | null;
    /**
     * <meta property=\"og:locale\" content=\"en_GB\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogLocale'?: string | null;
    /**
     * <meta property=\"og:locale:alternate\" content=\"fr_FR\" />  <meta property=\"og:locale:alternate\" content=\"es_ES\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogLocaleAlternate'?: string | null;
    /**
     * <meta property=\"og:site_name\" content=\"IMDb\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogSiteName'?: string | null;
    /**
     * <meta property=\"og:video\" content=\"https://example.com/bond/trailer.swf\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'ogVideo'?: string | null;
    /**
     * <meta name=\"twitter:card\" content=\"summary\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'twitterCard'?: string | null;
    /**
     * <meta name=\"twitter:site\" content=\"@yoursite\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'twitterSite'?: string | null;
    /**
     * <meta name=\"twitter:title\" content=\"Your Title\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'twitterTitle'?: string | null;
    /**
     * <meta name=\"twitter:description\" content=\"Your description.\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'twitterDescription'?: string | null;
    /**
     * <meta name=\"twitter:image\" content=\"https://where-your-image-is-hosted/name.jpg\" />
     * @type {string}
     * @memberof AdvisersLanding
     */
    'twitterImage'?: string | null;
}

