/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Advisers
 */
export interface Advisers {
    /**
     * 
     * @type {string}
     * @memberof Advisers
     */
    'adviserName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Advisers
     */
    'adviserPhone'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Advisers
     */
    'sellAdCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof Advisers
     */
    'letAdCount'?: number;
}

