/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AdviserToReturnDto
 */
export interface AdviserToReturnDto {
    /**
     * کد مشاور
     * @type {number}
     * @memberof AdviserToReturnDto
     */
    'id'?: number;
    /**
     * نام مشاور
     * @type {string}
     * @memberof AdviserToReturnDto
     */
    'name'?: string | null;
    /**
     * موبایل
     * @type {string}
     * @memberof AdviserToReturnDto
     */
    'mobile'?: string | null;
    /**
     * تصویر
     * @type {string}
     * @memberof AdviserToReturnDto
     */
    'profile'?: string | null;
    /**
     * نقش
     * @type {string}
     * @memberof AdviserToReturnDto
     */
    'role'?: string | null;
    /**
     * کد ملی
     * @type {string}
     * @memberof AdviserToReturnDto
     */
    'ncode'?: string | null;
    /**
     * ایمیل
     * @type {string}
     * @memberof AdviserToReturnDto
     */
    'email'?: string | null;
    /**
     * آخرین ورود
     * @type {string}
     * @memberof AdviserToReturnDto
     */
    'lastLogin'?: string | null;
    /**
     * کد شهر
     * @type {number}
     * @memberof AdviserToReturnDto
     */
    'cityId'?: number;
    /**
     * کد آژانس
     * @type {number}
     * @memberof AdviserToReturnDto
     */
    'agencyId'?: number;
    /**
     * نام آژانس
     * @type {string}
     * @memberof AdviserToReturnDto
     */
    'agencyName'?: string | null;
    /**
     * شماره تلفن آژانس
     * @type {string}
     * @memberof AdviserToReturnDto
     */
    'agencyPhone'?: string | null;
    /**
     * لوگو آژانس
     * @type {string}
     * @memberof AdviserToReturnDto
     */
    'agencyLogo'?: string | null;
    /**
     * شهر
     * @type {string}
     * @memberof AdviserToReturnDto
     */
    'cityName'?: string | null;
    /**
     * استان
     * @type {string}
     * @memberof AdviserToReturnDto
     */
    'provinceName'?: string | null;
    /**
     * کد استان
     * @type {number}
     * @memberof AdviserToReturnDto
     */
    'provinceId'?: number | null;
}

