/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AgencyRes } from './agency-res';

/**
 * 
 * @export
 * @interface AgencyResPagedList
 */
export interface AgencyResPagedList {
    /**
     * 
     * @type {Array<AgencyRes>}
     * @memberof AgencyResPagedList
     */
    'data'?: Array<AgencyRes> | null;
    /**
     * 
     * @type {number}
     * @memberof AgencyResPagedList
     */
    'currentPage'?: number;
    /**
     * 
     * @type {number}
     * @memberof AgencyResPagedList
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof AgencyResPagedList
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof AgencyResPagedList
     */
    'totalCount'?: number;
}

