/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AgencyClientToReturnDto
 */
export interface AgencyClientToReturnDto {
    /**
     * نام اژانس
     * @type {string}
     * @memberof AgencyClientToReturnDto
     */
    'agencyName'?: string | null;
    /**
     * شهر
     * @type {string}
     * @memberof AgencyClientToReturnDto
     */
    'city'?: string | null;
    /**
     * لوگو آژانس
     * @type {string}
     * @memberof AgencyClientToReturnDto
     */
    'agencyLogo'?: string | null;
    /**
     * تعداد مشاور
     * @type {number}
     * @memberof AgencyClientToReturnDto
     */
    'adviserCount'?: number;
}

