/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AgencyAdStatics
 */
export interface AgencyAdStatics {
    /**
     * لیبل
     * @type {string}
     * @memberof AgencyAdStatics
     */
    'label'?: string | null;
    /**
     * تعداد آگهی اجاره
     * @type {number}
     * @memberof AgencyAdStatics
     */
    'letCount'?: number;
    /**
     * تعداد آگهی فروش
     * @type {number}
     * @memberof AgencyAdStatics
     */
    'sellCount'?: number;
}

