/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { LogProps } from './log-props';

/**
 * 
 * @export
 * @interface AgencyActivityToReturnDto
 */
export interface AgencyActivityToReturnDto {
    /**
     * Id
     * @type {number}
     * @memberof AgencyActivityToReturnDto
     */
    'id'?: number;
    /**
     * Log Name
     * @type {string}
     * @memberof AgencyActivityToReturnDto
     */
    'logName'?: string | null;
    /**
     * Description
     * @type {string}
     * @memberof AgencyActivityToReturnDto
     */
    'description'?: string | null;
    /**
     * Subject Id
     * @type {number}
     * @memberof AgencyActivityToReturnDto
     */
    'subjectId'?: number | null;
    /**
     * Subject Type
     * @type {string}
     * @memberof AgencyActivityToReturnDto
     */
    'subjectType'?: string | null;
    /**
     * کد آژانس
     * @type {number}
     * @memberof AgencyActivityToReturnDto
     */
    'causerId'?: number | null;
    /**
     * 
     * @type {LogProps}
     * @memberof AgencyActivityToReturnDto
     */
    'properties'?: LogProps;
    /**
     * Created At
     * @type {string}
     * @memberof AgencyActivityToReturnDto
     */
    'createdAt'?: string | null;
}

