/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AgencyToReturnDto
 */
export interface AgencyToReturnDto {
    /**
     * رفرنس به آژانس
     * @type {number}
     * @memberof AgencyToReturnDto
     */
    'agencyId'?: number;
    /**
     * مالک آژانس
     * @type {number}
     * @memberof AgencyToReturnDto
     */
    'ownerId'?: number;
    /**
     * نام مالک
     * @type {string}
     * @memberof AgencyToReturnDto
     */
    'ownerName'?: string | null;
    /**
     * نام اژانس
     * @type {string}
     * @memberof AgencyToReturnDto
     */
    'agencyName'?: string | null;
    /**
     * لوگو آژانس
     * @type {string}
     * @memberof AgencyToReturnDto
     */
    'logo'?: string | null;
    /**
     * تلفن آژانس
     * @type {string}
     * @memberof AgencyToReturnDto
     */
    'phone'?: string | null;
    /**
     * استان
     * @type {string}
     * @memberof AgencyToReturnDto
     */
    'province'?: string | null;
    /**
     * شهر
     * @type {string}
     * @memberof AgencyToReturnDto
     */
    'city'?: string | null;
    /**
     * وضعیت
     * @type {string}
     * @memberof AgencyToReturnDto
     */
    'status'?: string | null;
    /**
     * کد رهگیری
     * @type {string}
     * @memberof AgencyToReturnDto
     */
    'trackingCode'?: string | null;
    /**
     * تاریخ ساخت
     * @type {string}
     * @memberof AgencyToReturnDto
     */
    'createdAt'?: string | null;
}

