/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AgencyDocumentForCreateDto
 */
export interface AgencyDocumentForCreateDto {
    /**
     * تلفن مسئول
     * @type {string}
     * @memberof AgencyDocumentForCreateDto
     */
    'phone1'?: string | null;
    /**
     * تلفن 2
     * @type {string}
     * @memberof AgencyDocumentForCreateDto
     */
    'phone2'?: string | null;
    /**
     * فکس
     * @type {string}
     * @memberof AgencyDocumentForCreateDto
     */
    'fax'?: string | null;
    /**
     * شماره جواز
     * @type {string}
     * @memberof AgencyDocumentForCreateDto
     */
    'certificateCode'?: string | null;
    /**
     * شرحی از آژانس
     * @type {string}
     * @memberof AgencyDocumentForCreateDto
     */
    'description'?: string | null;
    /**
     * آدرس آژانس مسکن
     * @type {string}
     * @memberof AgencyDocumentForCreateDto
     */
    'address'?: string | null;
    /**
     * بنر آژانس
     * @type {any}
     * @memberof AgencyDocumentForCreateDto
     */
    'banner'?: any | null;
    /**
     * جواز کسب
     * @type {any}
     * @memberof AgencyDocumentForCreateDto
     */
    'certificate'?: any | null;
}

