/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApkToReturnDto
 */
export interface ApkToReturnDto {
    /**
     * Version Name
     * @type {string}
     * @memberof ApkToReturnDto
     */
    'versionName'?: string | null;
    /**
     * Version Number
     * @type {string}
     * @memberof ApkToReturnDto
     */
    'versionNumber'?: string | null;
    /**
     * Path
     * @type {string}
     * @memberof ApkToReturnDto
     */
    'path'?: string | null;
    /**
     * Realease Note
     * @type {string}
     * @memberof ApkToReturnDto
     */
    'realeaseNote'?: string | null;
    /**
     * Required
     * @type {boolean}
     * @memberof ApkToReturnDto
     */
    'required'?: boolean;
    /**
     * Download
     * @type {number}
     * @memberof ApkToReturnDto
     */
    'download'?: number;
}

