/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AddressToReturnDto } from './address-to-return-dto';
import { ExistingFacilityDto } from './existing-facility-dto';
import { FacilityToReturnDto } from './facility-to-return-dto';
import { LandlordToReturnDto } from './landlord-to-return-dto';

/**
 * 
 * @export
 * @interface BuildingToReturnDto
 */
export interface BuildingToReturnDto {
    /**
     * کد ساختمان
     * @type {number}
     * @memberof BuildingToReturnDto
     */
    'buildingId'?: number;
    /**
     * کد پیگیری
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'trackingCode'?: string | null;
    /**
     * محله
     * @type {number}
     * @memberof BuildingToReturnDto
     */
    'neighbourhoodId'?: number;
    /**
     * نام محله
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'neibourhoodName'?: string | null;
    /**
     * نوع ساختمان
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'type'?: BuildingToReturnDtoTypeEnum;
    /**
     * قیمت توافقی که حذف شده و به نوع معامله انتقال پیدا کرده در اپ جدید
     * @type {boolean}
     * @memberof BuildingToReturnDto
     */
    'agreedPrice'?: boolean;
    /**
     * کاربری ساختمان
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'use'?: BuildingToReturnDtoUseEnum;
    /**
     * متراژ ملک
     * @type {number}
     * @memberof BuildingToReturnDto
     */
    'area'?: number;
    /**
     * نوع متراژ
     * @type {boolean}
     * @memberof BuildingToReturnDto
     */
    'areaType'?: boolean;
    /**
     * زیر بنا
     * @type {number}
     * @memberof BuildingToReturnDto
     */
    'foundation'?: number | null;
    /**
     * نوع سند
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'documentType'?: BuildingToReturnDtoDocumentTypeEnum;
    /**
     * شرایط فروش
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'condition'?: BuildingToReturnDtoConditionEnum;
    /**
     * موقعیت جغرافیایی
     * @type {Array<string>}
     * @memberof BuildingToReturnDto
     */
    'direction'?: Array<string> | null;
    /**
     * سال ساخت از 1360 تا کنون
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'buildingAge'?: string | null;
    /**
     * تعداد اتاق
     * @type {number}
     * @memberof BuildingToReturnDto
     */
    'rooms'?: number;
    /**
     * تعداد طبقات شامل ساختمان بدون طبقه یک طبقه دو طبقه تا...... شصت طبقه
     * @type {number}
     * @memberof BuildingToReturnDto
     */
    'floors'?: number;
    /**
     * طبقه چندم زیر همکف طبقه اول طبقه دوم تا...... طبقه شصتم
     * @type {number}
     * @memberof BuildingToReturnDto
     */
    'floorLevel'?: number;
    /**
     * شماره واحد
     * @type {number}
     * @memberof BuildingToReturnDto
     */
    'unit'?: number;
    /**
     * تعداد واحد شامل در این طبقه تک واحدی دو واحدی سه واحدی چهار واحدی پنج واحدی شش واحد یا بیشتر
     * @type {number}
     * @memberof BuildingToReturnDto
     */
    'unitPerLevel'?: number;
    /**
     * لوکیشن حاوی lat , lon
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'coordinate'?: string | null;
    /**
     * امتیاز سازه
     * @type {number}
     * @memberof BuildingToReturnDto
     */
    'ranking'?: number;
    /**
     * تاریخ تخلیه
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'availableDate'?: string | null;
    /**
     * 
     * @type {AddressToReturnDto}
     * @memberof BuildingToReturnDto
     */
    'address'?: AddressToReturnDto;
    /**
     * 
     * @type {FacilityToReturnDto}
     * @memberof BuildingToReturnDto
     */
    'facility'?: FacilityToReturnDto;
    /**
     * امکانات موجود
     * @type {Array<ExistingFacilityDto>}
     * @memberof BuildingToReturnDto
     */
    'existingFacilities'?: Array<ExistingFacilityDto> | null;
    /**
     * 
     * @type {LandlordToReturnDto}
     * @memberof BuildingToReturnDto
     */
    'landlord'?: LandlordToReturnDto;
    /**
     * آدرس فولدر عکس ها
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'photoPath'?: string | null;
    /**
     * لیست عکسها
     * @type {Array<string>}
     * @memberof BuildingToReturnDto
     */
    'photos'?: Array<string> | null;
    /**
     * آدرس ویدیوی آگهی  https://www.aparat.com/v/UCj85
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'video'?: string | null;
    /**
     * ایجاد شده در
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'createdAt'?: string | null;
    /**
     * ویرایش شده در
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'updatedAt'?: string | null;
    /**
     * حذف شده در
     * @type {string}
     * @memberof BuildingToReturnDto
     */
    'deletedAt'?: string | null;
}

export const BuildingToReturnDtoTypeEnum = {
    Apartment: 'Apartment',
    Home: 'Home',
    Villa: 'Villa',
    OldHouse: 'OldHouse',
    ResidentialLand: 'ResidentialLand',
    Garden: 'Garden',
    Office: 'Office',
    Shop: 'Shop',
    Clinic: 'Clinic',
    FarmLand: 'FarmLand',
    CommercialLand: 'CommercialLand',
    Store: 'Store',
    IndustrialShed: 'IndustrialShed',
    Workshop: 'Workshop',
    Factory: 'Factory',
    CoastalLand: 'CoastalLand'
} as const;

export type BuildingToReturnDtoTypeEnum = typeof BuildingToReturnDtoTypeEnum[keyof typeof BuildingToReturnDtoTypeEnum];
export const BuildingToReturnDtoUseEnum = {
    Residential: 'Residential',
    Commercial: 'Commercial',
    LandAndGarden: 'LandAndGarden',
    Industrial: 'Industrial',
    ResidentialProperties: 'ResidentialProperties',
    Apartment: 'Apartment',
    Villa: 'Villa',
    Home: 'Home',
    ResidentialLand: 'ResidentialLand',
    Garden: 'Garden',
    OldHouse: 'OldHouse',
    Farm: 'Farm',
    CommercialLand: 'CommercialLand',
    Office: 'Office',
    Clinic: 'Clinic',
    Store: 'Store',
    Shop: 'Shop',
    IndustrialShed: 'IndustrialShed',
    Factory: 'Factory'
} as const;

export type BuildingToReturnDtoUseEnum = typeof BuildingToReturnDtoUseEnum[keyof typeof BuildingToReturnDtoUseEnum];
export const BuildingToReturnDtoDocumentTypeEnum = {
    WrittenPromise: 'WrittenPromise',
    Certain: 'Certain',
    Mortgage: 'Mortgage',
    Advocacy: 'Advocacy',
    Endowment: 'Endowment',
    Common: 'Common',
    RightOfBusiness: 'RightOfBusiness',
    Ongoing: 'Ongoing',
    Other: 'Other'
} as const;

export type BuildingToReturnDtoDocumentTypeEnum = typeof BuildingToReturnDtoDocumentTypeEnum[keyof typeof BuildingToReturnDtoDocumentTypeEnum];
export const BuildingToReturnDtoConditionEnum = {
    CashSales: 'CashSales',
    Changeable: 'Changeable',
    Leasing: 'Leasing',
    Presell: 'Presell',
    ParticipationInConstruction: 'ParticipationInConstruction'
} as const;

export type BuildingToReturnDtoConditionEnum = typeof BuildingToReturnDtoConditionEnum[keyof typeof BuildingToReturnDtoConditionEnum];


