/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CallInforamtionToReturnDto
 */
export interface CallInforamtionToReturnDto {
    /**
     * لوگو آژانس
     * @type {string}
     * @memberof CallInforamtionToReturnDto
     */
    'agencyLogo'?: string | null;
    /**
     * نام آژانس
     * @type {string}
     * @memberof CallInforamtionToReturnDto
     */
    'agencyName'?: string | null;
    /**
     * پروفایل مشاور
     * @type {string}
     * @memberof CallInforamtionToReturnDto
     */
    'adviserProfile'?: string | null;
    /**
     * نام مشاور
     * @type {string}
     * @memberof CallInforamtionToReturnDto
     */
    'adviserName'?: string | null;
    /**
     * کد آگهی
     * @type {number}
     * @memberof CallInforamtionToReturnDto
     */
    'trackingCode'?: number;
    /**
     * موبایل مشاور
     * @type {string}
     * @memberof CallInforamtionToReturnDto
     */
    'adviserMobile'?: string | null;
    /**
     * تلفن آژانس
     * @type {string}
     * @memberof CallInforamtionToReturnDto
     */
    'agencyPhone'?: string | null;
}

