/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChangePasswordDto
 */
export interface ChangePasswordDto {
    /**
     * رمز فعلی
     * @type {string}
     * @memberof ChangePasswordDto
     */
    'currentPassword'?: string | null;
    /**
     * رمز جدید
     * @type {string}
     * @memberof ChangePasswordDto
     */
    'newPassword'?: string | null;
}

