/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ProductsDto } from './products-dto';

/**
 * 
 * @export
 * @interface ContractToReturnDto
 */
export interface ContractToReturnDto {
    /**
     * کد قرارداد
     * @type {number}
     * @memberof ContractToReturnDto
     */
    'id'?: number;
    /**
     * کد آژانس
     * @type {number}
     * @memberof ContractToReturnDto
     */
    'agencyId'?: number;
    /**
     * کد بسته
     * @type {number}
     * @memberof ContractToReturnDto
     */
    'packageId'?: number;
    /**
     * 
     * @type {ProductsDto}
     * @memberof ContractToReturnDto
     */
    'products'?: ProductsDto;
    /**
     * انقضا در
     * @type {string}
     * @memberof ContractToReturnDto
     */
    'expiredAt'?: string | null;
    /**
     * ایجاد شده در
     * @type {string}
     * @memberof ContractToReturnDto
     */
    'createdAt'?: string | null;
    /**
     * ویرایش شده در
     * @type {string}
     * @memberof ContractToReturnDto
     */
    'updatedAt'?: string | null;
    /**
     * حذف شده در
     * @type {string}
     * @memberof ContractToReturnDto
     */
    'deletedAt'?: string | null;
}

