/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePackageReq
 */
export interface CreatePackageReq {
    /**
     * کد محصول
     * @type {number}
     * @memberof CreatePackageReq
     */
    'productId'?: number;
    /**
     * تعداد
     * @type {number}
     * @memberof CreatePackageReq
     */
    'quantity'?: number;
}

