/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmployeeToReturnDto
 */
export interface EmployeeToReturnDto {
    /**
     * کد
     * @type {number}
     * @memberof EmployeeToReturnDto
     */
    'id'?: number;
    /**
     * کد نقش
     * @type {number}
     * @memberof EmployeeToReturnDto
     */
    'roleId'?: number;
    /**
     * نقش
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'roleName'?: string | null;
    /**
     * نام کامل
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'fullName'?: string | null;
    /**
     * ایمیل
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'email'?: string | null;
    /**
     * موبایل
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'mobile'?: string | null;
    /**
     * تصویر
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'profile'?: string | null;
    /**
     * تاریخ تولد
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'born'?: string | null;
    /**
     * کد ملی
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'ncode'?: string | null;
    /**
     * تلفن
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'phone'?: string | null;
    /**
     * آدرس
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'address'?: string | null;
    /**
     * شهر
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'city'?: string | null;
    /**
     * استان
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'province'?: string | null;
    /**
     * جنسیت
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'gender'?: string | null;
    /**
     * فعال
     * @type {boolean}
     * @memberof EmployeeToReturnDto
     */
    'active'?: boolean;
    /**
     * آخرین ورود
     * @type {string}
     * @memberof EmployeeToReturnDto
     */
    'lastLogin'?: string | null;
}

