/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FacilityForCreateDto
 */
export interface FacilityForCreateDto {
    /**
     * پارکینگ
     * @type {string}
     * @memberof FacilityForCreateDto
     */
    'parking'?: FacilityForCreateDtoParkingEnum;
    /**
     * کابینت اشپزخانه
     * @type {string}
     * @memberof FacilityForCreateDto
     */
    'kitchenUnit'?: FacilityForCreateDtoKitchenUnitEnum;
    /**
     * کف پوش
     * @type {string}
     * @memberof FacilityForCreateDto
     */
    'flooring'?: FacilityForCreateDtoFlooringEnum;
    /**
     * سیستم گرمایشی
     * @type {string}
     * @memberof FacilityForCreateDto
     */
    'heatingSystem'?: FacilityForCreateDtoHeatingSystemEnum;
    /**
     * اسانسور دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'lift'?: boolean | null;
    /**
     * انباری دارد یا نه
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'storage'?: boolean | null;
    /**
     * تراس دارد یا نه
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'teras'?: boolean | null;
    /**
     * کمد دیواری دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'wallCupboard'?: boolean | null;
    /**
     * حیاط دارد یا نه
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'yard'?: boolean | null;
    /**
     * راه جدا
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'separate'?: boolean | null;
    /**
     * آب دارد یا نه
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'water'?: boolean | null;
    /**
     * برق دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'electricity'?: boolean | null;
    /**
     * گاز دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'gas'?: boolean | null;
    /**
     * خط تلفن دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'landLine'?: boolean | null;
    /**
     * کولر
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'cooler'?: boolean | null;
    /**
     * درب ضد سرقت دارد یا نه
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'securityDoor'?: boolean | null;
    /**
     * اعلام حریق دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'fireAlarm'?: boolean | null;
    /**
     * دوربین مدار بسته دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'cctv'?: boolean | null;
    /**
     * دزدگیر دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'intruderAlarm'?: boolean | null;
    /**
     * آیفون تصویری دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'iphone'?: boolean | null;
    /**
     * درب ریموتی دارد یا نه
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'remoteDoor'?: boolean | null;
    /**
     * نورگیر دارد ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'lightning'?: boolean | null;
    /**
     * پرده دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'curtain'?: boolean | null;
    /**
     * کاغذ دیواری دارد یا نه
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'wallpaper'?: boolean | null;
    /**
     * دست شویی دارد یا نه
     * @type {number}
     * @memberof FacilityForCreateDto
     */
    'toilet'?: number | null;
    /**
     * دستشویی فرنگی دارد یا نه
     * @type {number}
     * @memberof FacilityForCreateDto
     */
    'toiletWc'?: number | null;
    /**
     * حمام دارد یا ندارد
     * @type {number}
     * @memberof FacilityForCreateDto
     */
    'bathroom'?: number | null;
    /**
     * وان حمام دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'bath'?: boolean | null;
    /**
     * استخر دارد یا نه
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'swimmingPool'?: boolean | null;
    /**
     * سونا دارد یا نه
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'sauna'?: boolean | null;
    /**
     * جکوزی دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'jacuzzi'?: boolean | null;
    /**
     * سالن ورزشی دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'gym'?: boolean | null;
    /**
     * لابی دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'lobby'?: boolean | null;
    /**
     * دوبلکس است یا خیر که در مشخصات ملک در اپ جدید حذف شده بود
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'duplex'?: boolean | null;
    /**
     * شومینه دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'fireplace'?: boolean | null;
    /**
     * شوتینگ دارد یا نه
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'shooting'?: boolean | null;
    /**
     * آب نما دارد یا ندارد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'fountain'?: boolean | null;
    /**
     * پنت هوپس که در اپ جدید حذف شده و در نکات کلیدی می توان وارد کرد
     * @type {boolean}
     * @memberof FacilityForCreateDto
     */
    'penthouse'?: boolean | null;
    /**
     * وام دارد یا ندارد
     * @type {string}
     * @memberof FacilityForCreateDto
     */
    'loan'?: string | null;
}

/**
    * @export
    * @enum {string}
    */
export enum FacilityForCreateDtoParkingEnum {
    DoesNotHave = 'DoesNotHave',
    Exclusive = 'Exclusive',
    Annoying = 'Annoying',
    NoAnnoying = 'NoAnnoying'
}
/**
    * @export
    * @enum {string}
    */
export enum FacilityForCreateDtoKitchenUnitEnum {
    DoesNotHave = 'DoesNotHave',
    Mdf = 'MDF',
    Metal = 'Metal',
    Membrane = 'Membrane'
}
/**
    * @export
    * @enum {string}
    */
export enum FacilityForCreateDtoFlooringEnum {
    Stone = 'Stone',
    Parquet = 'Parquet',
    Ceramic = 'Ceramic',
    Carpet = 'Carpet',
    Mosaic = 'Mosaic'
}
/**
    * @export
    * @enum {string}
    */
export enum FacilityForCreateDtoHeatingSystemEnum {
    Package = 'Package',
    Heater = 'Heater',
    CentralHeating = 'CentralHeating',
    UnderFloorHeating = 'UnderFloorHeating',
    Radiator = 'Radiator',
    Split = 'Split'
}


