/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FollowUpToReturnDto
 */
export interface FollowUpToReturnDto {
    /**
     * نام کارمند
     * @type {string}
     * @memberof FollowUpToReturnDto
     */
    'employeeName'?: string | null;
    /**
     * نام آژانس
     * @type {string}
     * @memberof FollowUpToReturnDto
     */
    'agencyName'?: string | null;
    /**
     * کد پیگیری آژانس
     * @type {string}
     * @memberof FollowUpToReturnDto
     */
    'agencyTrackingCode'?: string | null;
    /**
     * تلفن آژانس
     * @type {string}
     * @memberof FollowUpToReturnDto
     */
    'agencyPhone'?: string | null;
    /**
     * توضیحات
     * @type {string}
     * @memberof FollowUpToReturnDto
     */
    'description'?: string | null;
    /**
     * نوع پیگیری
     * @type {string}
     * @memberof FollowUpToReturnDto
     */
    'type'?: FollowUpToReturnDtoTypeEnum;
    /**
     * وضعیت پیگیری
     * @type {string}
     * @memberof FollowUpToReturnDto
     */
    'status'?: FollowUpToReturnDtoStatusEnum;
    /**
     * تایم یادآوری
     * @type {string}
     * @memberof FollowUpToReturnDto
     */
    'reminderTime'?: string | null;
    /**
     * تاریخ ایجاد
     * @type {string}
     * @memberof FollowUpToReturnDto
     */
    'creationTime'?: string | null;
    /**
     * تاریخ آپدیت
     * @type {string}
     * @memberof FollowUpToReturnDto
     */
    'updateTime'?: string | null;
    /**
     * کد پیگیری
     * @type {string}
     * @memberof FollowUpToReturnDto
     */
    'followUpCode'?: string | null;
    /**
     * کد آژانس
     * @type {number}
     * @memberof FollowUpToReturnDto
     */
    'agencyId'?: number;
    /**
     * کد  کارمند
     * @type {number}
     * @memberof FollowUpToReturnDto
     */
    'employeeId'?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum FollowUpToReturnDtoTypeEnum {
    Phone = 'phone',
    Contract = 'contract',
    Meeting = 'meeting',
    Visit = 'visit'
}
/**
    * @export
    * @enum {string}
    */
export enum FollowUpToReturnDtoStatusEnum {
    Record = 'record',
    Remind = 'remind'
}


