/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FollowUpForAgency
 */
export interface FollowUpForAgency {
    /**
     * 
     * @type {string}
     * @memberof FollowUpForAgency
     */
    'agencyName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FollowUpForAgency
     */
    'ownerName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FollowUpForAgency
     */
    'agencyTrackingCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FollowUpForAgency
     */
    'ownerMobile'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FollowUpForAgency
     */
    'agencyPhone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FollowUpForAgency
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FollowUpForAgency
     */
    'provinceName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FollowUpForAgency
     */
    'cityName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FollowUpForAgency
     */
    'workingTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FollowUpForAgency
     */
    'updatedAt'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof FollowUpForAgency
     */
    'advisers'?: Array<string> | null;
}

