/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupToReturnDto
 */
export interface GroupToReturnDto {
    /**
     * 
     * @type {number}
     * @memberof GroupToReturnDto
     */
    'groupId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupToReturnDto
     */
    'groupName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupToReturnDto
     */
    'context'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupToReturnDto
     */
    'createdAt'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GroupToReturnDto
     */
    'updatedAt'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GroupToReturnDto
     */
    'employeesCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof GroupToReturnDto
     */
    'agenciesCount'?: number;
}

