/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HelpForCreationDto
 */
export interface HelpForCreationDto {
    /**
     * طبقه بندی
     * @type {string}
     * @memberof HelpForCreationDto
     */
    'category'?: string | null;
    /**
     * تیتر
     * @type {string}
     * @memberof HelpForCreationDto
     */
    'title'?: string | null;
    /**
     * توضیحات
     * @type {string}
     * @memberof HelpForCreationDto
     */
    'description'?: string | null;
}

