/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LandlordToReturnDto
 */
export interface LandlordToReturnDto {
    /**
     * کد صاحب ملک
     * @type {number}
     * @memberof LandlordToReturnDto
     */
    'landlordId'?: number;
    /**
     * پیام صاحب ملک
     * @type {string}
     * @memberof LandlordToReturnDto
     */
    'message'?: string | null;
    /**
     * موبایل صاحب ملک
     * @type {string}
     * @memberof LandlordToReturnDto
     */
    'mobile'?: string | null;
    /**
     * اسم صاحب ملک
     * @type {string}
     * @memberof LandlordToReturnDto
     */
    'name'?: string | null;
    /**
     * تلفن صاحب ملک
     * @type {string}
     * @memberof LandlordToReturnDto
     */
    'phone'?: string | null;
}

