/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BuildingToReturnDto } from './building-to-return-dto';

/**
 * 
 * @export
 * @interface LetToReturnDto
 */
export interface LetToReturnDto {
    /**
     * کد اجاره
     * @type {number}
     * @memberof LetToReturnDto
     */
    'letId'?: number;
    /**
     * نام مشاور
     * @type {string}
     * @memberof LetToReturnDto
     */
    'adviserName'?: string | null;
    /**
     * کد مشاور
     * @type {number}
     * @memberof LetToReturnDto
     */
    'adviserId'?: number;
    /**
     * قیمت رهن
     * @type {number}
     * @memberof LetToReturnDto
     */
    'deposit'?: number;
    /**
     * قیمت اجاره
     * @type {number}
     * @memberof LetToReturnDto
     */
    'rent'?: number;
    /**
     * توضیحات
     * @type {string}
     * @memberof LetToReturnDto
     */
    'description'?: string | null;
    /**
     * نکات کلیدی
     * @type {Array<string>}
     * @memberof LetToReturnDto
     */
    'keyFeatures'?: Array<string> | null;
    /**
     * نوع آگهی
     * @type {string}
     * @memberof LetToReturnDto
     */
    'publishType'?: LetToReturnDtoPublishTypeEnum;
    /**
     * وضعیت آگهی
     * @type {string}
     * @memberof LetToReturnDto
     */
    'adStatus'?: string | null;
    /**
     * لینک
     * @type {string}
     * @memberof LetToReturnDto
     */
    'link'?: string | null;
    /**
     * 
     * @type {BuildingToReturnDto}
     * @memberof LetToReturnDto
     */
    'building'?: BuildingToReturnDto;
    /**
     * تعداد تصاویر
     * @type {number}
     * @memberof LetToReturnDto
     */
    'photos'?: number;
    /**
     * تاریخ و زمان منتشر شدن
     * @type {string}
     * @memberof LetToReturnDto
     */
    'publishedAt'?: string | null;
    /**
     * ایجاد شده در
     * @type {string}
     * @memberof LetToReturnDto
     */
    'createdAt'?: string | null;
    /**
     * ویرایش شده در
     * @type {string}
     * @memberof LetToReturnDto
     */
    'updatedAt'?: string | null;
    /**
     * حذف شده در
     * @type {string}
     * @memberof LetToReturnDto
     */
    'deletedAt'?: string | null;
}

export const LetToReturnDtoPublishTypeEnum = {
    Simple: 'simple',
    Occasion: 'occasion',
    Featured: 'featured'
} as const;

export type LetToReturnDtoPublishTypeEnum = typeof LetToReturnDtoPublishTypeEnum[keyof typeof LetToReturnDtoPublishTypeEnum];


