/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LogProps
 */
export interface LogProps {
    /**
     * 
     * @type {number}
     * @memberof LogProps
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof LogProps
     */
    'logger'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LogProps
     */
    'logger_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof LogProps
     */
    'logger_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LogProps
     */
    'ip'?: string | null;
}

