/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NeighbourhoodDto
 */
export interface NeighbourhoodDto {
    /**
     * کد
     * @type {number}
     * @memberof NeighbourhoodDto
     */
    'id'?: number;
    /**
     * کد شهر
     * @type {number}
     * @memberof NeighbourhoodDto
     */
    'cityId'?: number;
    /**
     * کد والد
     * @type {number}
     * @memberof NeighbourhoodDto
     */
    'parentId'?: number | null;
    /**
     * نام والد
     * @type {string}
     * @memberof NeighbourhoodDto
     */
    'parentName'?: string | null;
    /**
     * نام محله
     * @type {string}
     * @memberof NeighbourhoodDto
     */
    'name'?: string | null;
    /**
     * کد جد
     * @type {number}
     * @memberof NeighbourhoodDto
     */
    'ancestorId'?: number | null;
    /**
     * مختصات
     * @type {string}
     * @memberof NeighbourhoodDto
     */
    'location'?: string | null;
}

