/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PackageToReturnDto
 */
export interface PackageToReturnDto {
    /**
     * نام پکیج
     * @type {string}
     * @memberof PackageToReturnDto
     */
    'packageName'?: string | null;
    /**
     * قیمت
     * @type {string}
     * @memberof PackageToReturnDto
     */
    'price'?: string | null;
    /**
     * تاریخ ایجاد
     * @type {string}
     * @memberof PackageToReturnDto
     */
    'creationTime'?: string | null;
    /**
     * مدت زمان اعتبار
     * @type {string}
     * @memberof PackageToReturnDto
     */
    'duration'?: string | null;
    /**
     * فعال
     * @type {boolean}
     * @memberof PackageToReturnDto
     */
    'active'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PackageToReturnDto
     */
    'count'?: number;
}

