/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductsToReturnDto
 */
export interface ProductsToReturnDto {
    /**
     * کد محصول
     * @type {number}
     * @memberof ProductsToReturnDto
     */
    'productId'?: number;
    /**
     * نام محصول
     * @type {string}
     * @memberof ProductsToReturnDto
     */
    'name'?: string | null;
    /**
     * نام فارسی محصول
     * @type {string}
     * @memberof ProductsToReturnDto
     */
    'displayName'?: string | null;
    /**
     * قیمت محصول
     * @type {string}
     * @memberof ProductsToReturnDto
     */
    'price'?: string | null;
    /**
     * نوع محصول
     * @type {boolean}
     * @memberof ProductsToReturnDto
     */
    'productType'?: boolean;
    /**
     * تاریخ ایجاد محصول
     * @type {string}
     * @memberof ProductsToReturnDto
     */
    'createdAt'?: string | null;
    /**
     * تاریخ اپدیت محصول
     * @type {string}
     * @memberof ProductsToReturnDto
     */
    'updatedAt'?: string | null;
    /**
     * تاریخ حذف محصول
     * @type {string}
     * @memberof ProductsToReturnDto
     */
    'deletedAt'?: string | null;
}

