/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * {\"occasion\":25,\"featured\":50,\"simple\":9049,\"republish\":75,\"logo\":1,\"panorama\":0,\"sban\":1,\"sbanMobile\":0,\"bannerMobile\":0,\"banner\":1,\"teaser\":0,\"voice\":0,\"blogAd\":1,\"topBanner\":0,\"topBannerMobile\":0,\"specialIntro\":0}
 * @export
 * @interface ProductsDto
 */
export interface ProductsDto {
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'occasion'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'featured'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'simple'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'republish'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'logo'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'panorama'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'sban'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'sbanMobile'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'bannerMobile'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'banner'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'teaser'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'voice'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'blogAd'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'topBanner'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'topBannerMobile'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductsDto
     */
    'specialIntro'?: number;
}

