/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductsDto
 */
export interface ProductsDto {
    /**
     * فوری
     * @type {number}
     * @memberof ProductsDto
     */
    'occasion'?: number;
    /**
     * ویژه
     * @type {number}
     * @memberof ProductsDto
     */
    'featured'?: number;
    /**
     * ساده
     * @type {number}
     * @memberof ProductsDto
     */
    'simple'?: number;
    /**
     * بازنشر
     * @type {number}
     * @memberof ProductsDto
     */
    'republish'?: number;
    /**
     * لوگو
     * @type {number}
     * @memberof ProductsDto
     */
    'logo'?: number | null;
    /**
     * پاناروما
     * @type {number}
     * @memberof ProductsDto
     */
    'panorama'?: number;
    /**
     * ساید بنر
     * @type {number}
     * @memberof ProductsDto
     */
    'sban'?: number;
    /**
     * ساید بنر موبایل
     * @type {number}
     * @memberof ProductsDto
     */
    'sbanMobile'?: number;
    /**
     * بنر موبایل
     * @type {number}
     * @memberof ProductsDto
     */
    'bannerMobile'?: number;
    /**
     * بنر
     * @type {number}
     * @memberof ProductsDto
     */
    'banner'?: number;
    /**
     * تیزر
     * @type {number}
     * @memberof ProductsDto
     */
    'teaser'?: number;
    /**
     * صدا
     * @type {number}
     * @memberof ProductsDto
     */
    'voice'?: number;
    /**
     * آگهی بلاگ
     * @type {number}
     * @memberof ProductsDto
     */
    'blogAd'?: number;
    /**
     * بنر بالایی
     * @type {number}
     * @memberof ProductsDto
     */
    'topBanner'?: number;
    /**
     * بنر بالایی موبایل
     * @type {number}
     * @memberof ProductsDto
     */
    'topBannerMobile'?: number;
    /**
     * معرفی ویژه
     * @type {number}
     * @memberof ProductsDto
     */
    'specialIntro'?: number;
}

