/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ForSaleBuildingForCreateDto } from './for-sale-building-for-create-dto';

/**
 * 
 * @export
 * @interface SellForCreateDto
 */
export interface SellForCreateDto {
    /**
     * قیمت
     * @type {number}
     * @memberof SellForCreateDto
     */
    'price'?: number;
    /**
     * توضیحات
     * @type {string}
     * @memberof SellForCreateDto
     */
    'description'?: string | null;
    /**
     * نکات کلیدی
     * @type {Array<string>}
     * @memberof SellForCreateDto
     */
    'keyFeatures'?: Array<string> | null;
    /**
     * نوع آگهی
     * @type {string}
     * @memberof SellForCreateDto
     */
    'publishType'?: SellForCreateDtoPublishTypeEnum;
    /**
     * 
     * @type {ForSaleBuildingForCreateDto}
     * @memberof SellForCreateDto
     */
    'building'?: ForSaleBuildingForCreateDto;
    /**
     * کد مشاور
     * @type {number}
     * @memberof SellForCreateDto
     */
    'adviserId'?: number;
}

export const SellForCreateDtoPublishTypeEnum = {
    Simple: 'simple',
    Occasion: 'occasion',
    Featured: 'featured'
} as const;

export type SellForCreateDtoPublishTypeEnum = typeof SellForCreateDtoPublishTypeEnum[keyof typeof SellForCreateDtoPublishTypeEnum];


