/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SellAd
 */
export interface SellAd {
    /**
     * 
     * @type {number}
     * @memberof SellAd
     */
    'sellId'?: number;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'price'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'publishType'?: SellAdPublishTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof SellAd
     */
    'neighbourhoodId'?: number;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'neibourhoodName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'buildingType'?: SellAdBuildingTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof SellAd
     */
    'area'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SellAd
     */
    'areaType'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SellAd
     */
    'rooms'?: number;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'photoPath'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SellAd
     */
    'photos'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'publishedAt'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SellAd
     */
    'cityId'?: number;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'cityName'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SellAd
     */
    'buildingId'?: number;
    /**
     * 
     * @type {number}
     * @memberof SellAd
     */
    'trackingCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'slug'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SellAd
     */
    'agencyId'?: number;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'agencyName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'agencyLogo'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SellAd
     */
    'adviserId'?: number;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'adviserName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'link'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'createdAt'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SellAd
     */
    'storage'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof SellAd
     */
    'yard'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof SellAd
     */
    'seprate'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof SellAd
     */
    'lift'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'parking'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'mainAddress'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'unitPerLevel'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'unit'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'floorLevel'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SellAd
     */
    'floors'?: string | null;
}

/**
    * @export
    * @enum {string}
    */
export enum SellAdPublishTypeEnum {
    Simple = 'simple',
    Occasion = 'occasion',
    Featured = 'featured'
}
/**
    * @export
    * @enum {string}
    */
export enum SellAdBuildingTypeEnum {
    Apartment = 'Apartment',
    Home = 'Home',
    Villa = 'Villa',
    OldHouse = 'OldHouse',
    ResidentialLand = 'ResidentialLand',
    Garden = 'Garden',
    Office = 'Office',
    Shop = 'Shop',
    Clinic = 'Clinic',
    FarmLand = 'FarmLand',
    CommercialLand = 'CommercialLand',
    Store = 'Store',
    IndustrialShed = 'IndustrialShed',
    Workshop = 'Workshop',
    Factory = 'Factory',
    CoastalLand = 'CoastalLand'
}


