/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BuildingToReturnDto } from './building-to-return-dto';

/**
 * 
 * @export
 * @interface SellToReturnDto
 */
export interface SellToReturnDto {
    /**
     * کد فروش
     * @type {number}
     * @memberof SellToReturnDto
     */
    'sellId'?: number;
    /**
     * نام مشاور
     * @type {string}
     * @memberof SellToReturnDto
     */
    'adviserName'?: string | null;
    /**
     * کد مشاور
     * @type {number}
     * @memberof SellToReturnDto
     */
    'adviserId'?: number;
    /**
     * قیمت
     * @type {number}
     * @memberof SellToReturnDto
     */
    'price'?: number;
    /**
     * توضیحات
     * @type {string}
     * @memberof SellToReturnDto
     */
    'description'?: string | null;
    /**
     * نکات کلیدی
     * @type {Array<string>}
     * @memberof SellToReturnDto
     */
    'keyFeatures'?: Array<string> | null;
    /**
     * نوع آگهی
     * @type {string}
     * @memberof SellToReturnDto
     */
    'publishType'?: SellToReturnDtoPublishTypeEnum;
    /**
     * وضعیت آگهی
     * @type {string}
     * @memberof SellToReturnDto
     */
    'adStatus'?: string | null;
    /**
     * لینک
     * @type {string}
     * @memberof SellToReturnDto
     */
    'link'?: string | null;
    /**
     * 
     * @type {BuildingToReturnDto}
     * @memberof SellToReturnDto
     */
    'building'?: BuildingToReturnDto;
    /**
     * منتشر شده در
     * @type {string}
     * @memberof SellToReturnDto
     */
    'publishedAt'?: string | null;
    /**
     * ایجاد شده در
     * @type {string}
     * @memberof SellToReturnDto
     */
    'createdAt'?: string | null;
    /**
     * ویرایش شده در
     * @type {string}
     * @memberof SellToReturnDto
     */
    'updatedAt'?: string | null;
    /**
     * حذف شده در
     * @type {string}
     * @memberof SellToReturnDto
     */
    'deletedAt'?: string | null;
}

export const SellToReturnDtoPublishTypeEnum = {
    Simple: 'simple',
    Occasion: 'occasion',
    Featured: 'featured'
} as const;

export type SellToReturnDtoPublishTypeEnum = typeof SellToReturnDtoPublishTypeEnum[keyof typeof SellToReturnDtoPublishTypeEnum];


