/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AddressForCreateDto } from './address-for-create-dto';
import { FacilityForCreateDto } from './facility-for-create-dto';
import { LandlordForCreateDto } from './landlord-for-create-dto';

/**
 * اطلاعات ساختمان جهت ثبت
 * @export
 * @interface ToRentBuildingForCreateDto
 */
export interface ToRentBuildingForCreateDto {
    /**
     * محله
     * @type {number}
     * @memberof ToRentBuildingForCreateDto
     */
    'neighbourhoodId'?: number;
    /**
     * (نوع ملک شامل  املاک مسکونی {خانه آپارتمان ویلا کلنگی} املاک تجاری {دفتر کار مغازه مطب} زمین و باغ {زمین مسکونی  زمین زراعی زمین تجاری باغ زمین ساحلی} صنعتی {انبار سوله کارگاه کارخانه
     * @type {string}
     * @memberof ToRentBuildingForCreateDto
     */
    'type'?: ToRentBuildingForCreateDtoTypeEnum;
    /**
     * قیمت توافقی که حذف شده و به نوع معامله انتقال پیدا کرده در اپ جدید
     * @type {boolean}
     * @memberof ToRentBuildingForCreateDto
     */
    'agreedPrice'?: boolean;
    /**
     * کاربری
     * @type {string}
     * @memberof ToRentBuildingForCreateDto
     */
    'use'?: ToRentBuildingForCreateDtoUseEnum;
    /**
     * متراژ ملک
     * @type {number}
     * @memberof ToRentBuildingForCreateDto
     */
    'area'?: number;
    /**
     * نوع متراژ
     * @type {boolean}
     * @memberof ToRentBuildingForCreateDto
     */
    'areaType'?: boolean;
    /**
     * زیر بنا
     * @type {number}
     * @memberof ToRentBuildingForCreateDto
     */
    'foundation'?: number | null;
    /**
     * نوع سند  شامل قطعی قولنامه رهنی وکالتی اوقافی مشاع سرقفلی در دست اقدام سایر
     * @type {string}
     * @memberof ToRentBuildingForCreateDto
     */
    'documentType'?: ToRentBuildingForCreateDtoDocumentTypeEnum;
    /**
     * شرایط فروش
     * @type {string}
     * @memberof ToRentBuildingForCreateDto
     */
    'condition'?: ToRentBuildingForCreateDtoConditionEnum;
    /**
     * موقعیت جغرافیایی شامل شمالی جنوبی شرقی غربی شمالی جنوبی شمالی غربی شمالی شرقی جنوبی غربی جنوبی شرقی شمالی جنوبی  غربی شمالی جنوبی شرقی
     * @type {Array<string>}
     * @memberof ToRentBuildingForCreateDto
     */
    'direction'?: Array<string> | null;
    /**
     * سال ساخت از 1360 تا کنون
     * @type {string}
     * @memberof ToRentBuildingForCreateDto
     */
    'buildingAge'?: string | null;
    /**
     * تعداد اتاق
     * @type {number}
     * @memberof ToRentBuildingForCreateDto
     */
    'rooms'?: number | null;
    /**
     * تعداد طبقات شامل ساختمان بدون طبقه یک طبقه دو طبقه تا...... شصت طبقه
     * @type {number}
     * @memberof ToRentBuildingForCreateDto
     */
    'floors'?: number | null;
    /**
     * طبقه چندم زیر همکف طبقه اول طبقه دوم تا...... طبقه شصتم
     * @type {number}
     * @memberof ToRentBuildingForCreateDto
     */
    'floorLevel'?: number | null;
    /**
     * شماره واحد
     * @type {number}
     * @memberof ToRentBuildingForCreateDto
     */
    'unit'?: number | null;
    /**
     * تعداد واحد شامل در این طبقه تک واحدی دو واحدی سه واحدی چهار واحدی پنج واحدی شش واحد یا بیشتر
     * @type {number}
     * @memberof ToRentBuildingForCreateDto
     */
    'unitPerLevel'?: number | null;
    /**
     * لوکیشن حاوی lat , lan
     * @type {string}
     * @memberof ToRentBuildingForCreateDto
     */
    'coordinate'?: string | null;
    /**
     * rank
     * @type {number}
     * @memberof ToRentBuildingForCreateDto
     */
    'ranking'?: number | null;
    /**
     * تاریخ تخلیه
     * @type {string}
     * @memberof ToRentBuildingForCreateDto
     */
    'availableDate'?: string | null;
    /**
     * آدرس ملک
     * @type {Array<AddressForCreateDto>}
     * @memberof ToRentBuildingForCreateDto
     */
    'address'?: Array<AddressForCreateDto> | null;
    /**
     * 
     * @type {FacilityForCreateDto}
     * @memberof ToRentBuildingForCreateDto
     */
    'facility'?: FacilityForCreateDto;
    /**
     * 
     * @type {LandlordForCreateDto}
     * @memberof ToRentBuildingForCreateDto
     */
    'landlord'?: LandlordForCreateDto;
    /**
     * آدرس ویدیوی آگهی  https://www.aparat.com/v/UCj85
     * @type {string}
     * @memberof ToRentBuildingForCreateDto
     */
    'video'?: string | null;
}

export const ToRentBuildingForCreateDtoTypeEnum = {
    Apartment: 'Apartment',
    Home: 'Home',
    Villa: 'Villa',
    OldHouse: 'OldHouse',
    ResidentialLand: 'ResidentialLand',
    Garden: 'Garden',
    Office: 'Office',
    Shop: 'Shop',
    Clinic: 'Clinic',
    FarmLand: 'FarmLand',
    CommercialLand: 'CommercialLand',
    Store: 'Store',
    IndustrialShed: 'IndustrialShed',
    Workshop: 'Workshop',
    Factory: 'Factory',
    CoastalLand: 'CoastalLand'
} as const;

export type ToRentBuildingForCreateDtoTypeEnum = typeof ToRentBuildingForCreateDtoTypeEnum[keyof typeof ToRentBuildingForCreateDtoTypeEnum];
export const ToRentBuildingForCreateDtoUseEnum = {
    Residential: 'Residential',
    Commercial: 'Commercial',
    LandAndGarden: 'LandAndGarden',
    Industrial: 'Industrial',
    ResidentialProperties: 'ResidentialProperties',
    Apartment: 'Apartment',
    Villa: 'Villa',
    Home: 'Home',
    ResidentialLand: 'ResidentialLand',
    Garden: 'Garden',
    OldHouse: 'OldHouse',
    Farm: 'Farm',
    CommercialLand: 'CommercialLand',
    Office: 'Office',
    Clinic: 'Clinic',
    Store: 'Store',
    Shop: 'Shop',
    IndustrialShed: 'IndustrialShed',
    Factory: 'Factory'
} as const;

export type ToRentBuildingForCreateDtoUseEnum = typeof ToRentBuildingForCreateDtoUseEnum[keyof typeof ToRentBuildingForCreateDtoUseEnum];
export const ToRentBuildingForCreateDtoDocumentTypeEnum = {
    WrittenPromise: 'WrittenPromise',
    Certain: 'Certain',
    Mortgage: 'Mortgage',
    Advocacy: 'Advocacy',
    Endowment: 'Endowment',
    Common: 'Common',
    RightOfBusiness: 'RightOfBusiness',
    Ongoing: 'Ongoing',
    Other: 'Other'
} as const;

export type ToRentBuildingForCreateDtoDocumentTypeEnum = typeof ToRentBuildingForCreateDtoDocumentTypeEnum[keyof typeof ToRentBuildingForCreateDtoDocumentTypeEnum];
export const ToRentBuildingForCreateDtoConditionEnum = {
    NonConvertible: 'NonConvertible',
    Convertable: 'Convertable'
} as const;

export type ToRentBuildingForCreateDtoConditionEnum = typeof ToRentBuildingForCreateDtoConditionEnum[keyof typeof ToRentBuildingForCreateDtoConditionEnum];


