/* tslint:disable */
/* eslint-disable */
/**
 * ای پی آی زومیلا
 * راهنمای استفاده از رابط برنامه نویسی نرم افزار زومیلا
 *
 * The version of the OpenAPI document: v1
 * Contact: jzabihi1980@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VilaToReturnDto
 */
export interface VilaToReturnDto {
    /**
     * 
     * @type {string}
     * @memberof VilaToReturnDto
     */
    'title'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VilaToReturnDto
     */
    'cityName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VilaToReturnDto
     */
    'photo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VilaToReturnDto
     */
    'price'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof VilaToReturnDto
     */
    'adId'?: number;
    /**
     * 
     * @type {string}
     * @memberof VilaToReturnDto
     */
    'link'?: string | null;
}

